### ISSUE TITLE
mruby head breaks build

### ISSUE THREAD

**Issue by hone** [hone/mruby-cli#23]
Seeing these two failures:

```
/tmp/d20151002-93-1okckhj/hello_world/mruby/test/report.rb:3:in `<top (required)>': mrbtest failed (KO:1, Crash:0) (RuntimeError)
    from test/bintest.rb:18:in `load'
    from test/bintest.rb:18:in `<main>'
rake aborted!
Command failed with status (1): [ruby test/bintest.rb "/tmp/d20151002-93-1o...]
/tmp/d20151002-93-1okckhj/hello_world/mruby/tasks/mruby_build.rake:276:in `run_bintest'
/tmp/d20151002-93-1okckhj/hello_world/Rakefile:52:in `block (4 levels) in <top (required)>'
/tmp/d20151002-93-1okckhj/hello_world/Rakefile:42:in `clean_env'
/tmp/d20151002-93-1okckhj/hello_world/Rakefile:51:in `block (3 levels) in <top (required)>'
/tmp/d20151002-93-1okckhj/hello_world/mruby/tasks/mruby_build.rake:13:in `instance_eval'
/tmp/d20151002-93-1okckhj/hello_world/mruby/tasks/mruby_build.rake:13:in `block in each_target'
/tmp/d20151002-93-1okckhj/hello_world/mruby/tasks/mruby_build.rake:12:in `each'
/tmp/d20151002-93-1okckhj/hello_world/mruby/tasks/mruby_build.rake:12:in `each_target'
/tmp/d20151002-93-1okckhj/hello_world/Rakefile:50:in `block (2 levels) in <top (required)>'
Tasks: TOP => test:bintest
(See full trace by running task with --trace)
```

```
Fail: setup can compile and run the generated app
 - Assertion[6] Failed: Process did not exit cleanly
    Expected: true
      Actual: false
Fail: Compiling multiple files without new line in last line. #2361
 - Assertion[1] Failed: Expected to be equal
    Expected: "bin\\mrbc.exe:/tmp/a.rb20151002-93-1tide85:Syntax OK"
      Actual: "sh: 1: binmrbc.exe: not found"
 - Assertion[2] Failed: Expected to be equal
    Expected: 0
      Actual: 127
```

[Link to Travis](https://travis-ci.org/hone/mruby-cli/builds/83223042)

**Comment by hone** [comment]
When running the bintests inside of a generated mruby-cli app, you get this failure.

```
..F
Fail: Compiling multiple files without new line in last line. #2361
 - Assertion[1] Failed: Expected to be equal
    Expected: "bin\\mrbc.exe:/tmp/a.rb20151002-1518-1rwlvnq:Syntax OK"
      Actual: "sh: 1: binmrbc.exe: not found"
 - Assertion[2] Failed: Expected to be equal
    Expected: 0
      Actual: 127
Total: 3
   OK: 2
   KO: 1
Crash: 0
 Time: 0.05 seconds
/home/mruby/code/mruby/test/report.rb:3:in `<top (required)>': mrbtest failed (KO:1, Crash:0) (RuntimeError)
        from test/bintest.rb:18:in `load'
        from test/bintest.rb:18:in `<main>'
```

Reverting [this commit](https://github.com/mruby/mruby/commit/545d649eff73021d515f7a96841b363b0001e9d9) fixes it.

Any ideas @mattn?

**Comment by mattn** [comment]
do you set `$SHELL` environment variable?

**Comment by toch** [comment]
@zzak thanks!

**Comment by zzak** [comment]
@toch Does this work if you `docker pull hone/mruby-cli:latest`?

**Comment by hone** [comment]
@mattn no we don't, is that now a requirement?

**Comment by mattn** [comment]
Could you please show me the log? If you set $SHELL, paths should be treated as slash separator.

**Comment by zzak** [comment]
We do as of zzak/mruby-cli-docker@6df6d158c856fd5c9bb61453dceec3f042f0cee8
